
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 11 22:19:54 COT 2015
//----------------------------------------------------

package compilador_calcular;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int A = 2;
  public static final int error = 1;
  public static final int NUMBER = 5;
  public static final int P = 3;
  public static final int PUNTOCOMA = 4;
  public static final int EOF = 0;
}

